language: android
  android:
    components:
      - tools
      - build-tools-25.0.2
      - platform-tools
      - extra

      # SDK Version to compile project
      - android-25
      - android-17
    licenses:
      - android-sdk-license-.+
      - '.+'
  
  jdk: oraclejdk8

before_script:
  - chmod +x gradlew

script:
  - ./gradlew assembleRelease --stacktrace